project:
  type: book
  comments: 
    hypothesis: true

# https://quarto.org/docs/computations/execution-options.html    
# for cell options: https://quarto.org/docs/reference/cells/cells-knitr.html
execute:
  eval: true
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  

book:
  title: "MTA baseline"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "Project notes"
      chapters:
      - intro/goals.qmd
      - intro/schedule.qmd
      - intro/boyd_questions.qmd
      - intro/data_notes.qmd
      - intro/resources.qmd
      - intro/misc_notes.qmd
    - part: "Taxes"
      chapters: 
      - taxes/current_taxes.qmd
      - taxes/payroll_mobility_tax.qmd
      - taxes/petroleum_business_tax.qmd
      - taxes/mortgage_recording_tax.qmd
    - part: "MTOA and MMTOA"
      chapters: 
      - mtoa/mtoa.qmd
    - part: "Payroll mobility tax base"
      chapters:
      - pmtbase/payroll_mobility_tax_base.qmd
    - part: "Options"
      chapters: 
      - options/options.qmd
    - bibliography.qmd


bibliography: _baseline.bib
nocite: |
  @*


format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt



