# Priorities and Agendas

## Current High Priorities:

-   Tax package related to digital economy and WFH

-   Extend estimates of marketplace tax

-   18b diversion 1996-plus; growth with inflation

-   MMTOA tracking collections, receipts, appropriations

-   Policy-oriented primers on selected taxes -- base, rate, history, interaction with other taxes, other relevant issues

    -   Noncorporate entities (partnerships, LLCs, trusts, etc.)

        -   Tax treatment generally

        -   Pass-through entity tax

    -   MTA corporate surcharge

    -   MTA sales tax

## Agendas

<!-- (taxes/payroll_mobility_tax.qmd#incidence) -->

<!-- quarto publish netlify --no-browser --no-prompt -->

<!-- quarto publish netlify --no-render --no-browser --no-prompt -->

### December 16, 2022, Friday

-   [PMT option to raise \$700 million](options/pmt_increase_dec2022.qmd), with and without state offset for legal changes

### December 12, 2022, Monday

-   [Digital sales tax package](options/sales_tax_digital.qmd)

-   [Internet marketplace tax update](primers/primer_internet_marketplace_tax.qmd)

-   [Section 18-b](primers/primer_section_18b.qmd) maybe

### December 9, 2022, Friday

-   [Section 18-b](primers/primer_section_18b.qmd)

-   [Digital sales tax package](options/sales_tax_digital.qmd)

-   [Internet marketplace tax update](primers/primer_internet_marketplace_tax.qmd)

### December 2, 2022, Friday

-   Review high priority items for Wed Dec 7

-   Discuss revenue package

### November 18, 2022, Friday

-   [Sales tax on video streaming services](options/sales_tax_video_streaming.qmd)

-   [Petroleum business tax](taxes/petroleum_business_tax.qmd)

-   [Internet marketplace tax - in progress](primers/primer_internet_marketplace_tax.qmd) -- can we track/calculate it, how much is it, change over time, how it compares to what state actually gives

### November 9, 2022, Wednesday

-   Comments on the preliminary options list from Kevin -- originally provided in a Google doc:

    -   [Key points](options/comments_2022_11_09.qmd)

    -   Annotated [spreadsheet](https://docs.google.com/spreadsheets/d/1lzmDe7Zj1fQ4jDk9och5FPGFEMEYKkk2Og_UKkH0soY/edit#gid=1406156042)

-   Taxation related to [internet access (prelim)](options/taxing_internet_access.qmd)

-   Sales tax on [aviation fuel - New Jersey](options/sales_tax_aviation_fuel.qmd)

-   Sales tax on [capital improvement installation services](options/sales_tax_capital_improvements.qmd)

### November 3, 2022, Thursday

-   Add columns to table on employment growth after PMT was adopted for suburban counties

### November 2, 2022, Wednesday, 3 pm

Near-term priorities ordered from highest to lowest. For any items that result in tables or graphs, provide links to a spreadsheet with data needed to produce MTA-prepared versions of same. Prepare as much of the following by Monday Oct 31:

-   Examine impact of PMT, starting with simplest approach (see [this](option_analysis/pmt_howlarge.qmd), [this](option_analysis/pmt_impact_employment.qmd), and [this](option_analysis/pmt_payroll_tax_rates.qmd))

    -   How large is the PMT relative to selected other taxes?

        -   as share of the economy (MTA corporate surcharge, NYS and NYC corporate taxes); **DONE**

        -   rates relative to other payroll taxes (table comparing rates of payroll taxes (FICA, FUTA, unemployment, PMT; make note of caps on payroll, and any substantial credits against tax; give links to sources)**IN PROGRESS**

    -   What happened to employment in MTA region *after* imposition of PMT (not *before and after*, as in the pre-post comparison discussed next)?

        -   compared to NYS, and compared to a of MTA-neighboring counties combined (NY, NJ, CT); **DONE**

    -   Same pre-post comparison of MTA counties and non-MTA neighbors as in the October 25 analysis, but add links to data for the graphs, **DONE**

    -   How much does the PMT worsen NY's tax ranking - what would happen to NY's ranking (state and local taxes relative to the economy) if the PMT did not exist? **DONE**

-   TCJA and MTA taxes see [this](option_analysis/pmt_tcja_ptet.qmd)

    -   How much did NY-ers save federally as a result of the pass-through entity tax? How does that compare to the size of a hypothetical PMT increase? **DONE**

    -   Possibly later (not near term priority): How much did NY-ers save federally from the TCJA?

-   Policy-oriented primers on selected other taxes -- base, rate, history, interaction with other taxes, other relevant issues

    -   Noncorporate entities (partnerships, LLCs, trusts, etc.)

        -   Tax treatment generally

        -   Pass-through entity tax

    -   MTA corporate surcharge

    -   MTA sales tax

-   Above info will make it easy to check a couple of the slides we looked at on Oct 28; highlight anything that needs to change.

### October 28, 2022

Review priorities for next items (see Nov 2 agenda above).

### October 25, 2022

As much of following as practical, in priority order. I have gotten as far as the horizontal rule below. click on the links below:

-   For [hypothetical PMT increase from 0.34% to 0.50%](option_analysis/pmt_increase.qmd)

    -   MCTD-wide impact, by size of employer

    -   By city/suburbs, by size of employer

    -   Crossed with work-from-home and non-work-from-home industries

    -   By average industry pay

-   Ways to analyze [impact of PMT on the economy](option_analysis/pmt_impact_employment.qmd)

    -   Pre- and post- employment in MTA and other regions

    ------------------------------------------------------------------------

    -   Size of PMT vs other taxes

        -   For a few representative or hypothetical firms, or for

        -   MTA region as a whole

-   For PMT increase, how much would exemptions change? How would state reimbursement change if adjusted? (Also, other state reimbursement issues we discussed - e.g., growth at inflation rate.)

-   Responsiveness of employment and wages, and PMT revenue, to PMT rate increase

-   Has PMT base changed much post-COVID?

-   Sales tax increase

    -   Table of current sales tax treatment - rows are NYC and MTA counties, columns are selected items (food, clothing, utilities, other), cells are treatment by state, local, and MTA sales taxes

    -   Spending by consumers in MTA region by income range on these goods and services

-   NYC financial plan much worse than state. State fiscal cliff with expiring millionaire's tax (surcharge). Corporate tax increase phaseout. Opportunity for MTA?

### October 21, 2022

-   Catch up generally, latest priorities and schedule

-   [Breakdowns of taxes](option_analysis/breakdowns.qmd) status and next steps

### September 20, 2022

-   [County allocation of baseline tax revenue - status and next steps](countyalloc/county_allocation.qmd)

*Go to section on Preliminary allocation results*

### September 16, 2022

-   County allocation of baseline tax revenue - status and next steps(countyalloc/county_allocation.qmd)

-   To Come: Internet marketplace - can we measure the true amount? how does it compare? what about the growth rate?

-   Next call

-   Contract status

### September 9, 2022

-   [County allocation of baseline tax revenue - status and next steps](countyalloc/county_allocation.qmd)

-   [The law on PMT tax changes](pmtbase/pmt_legislation.qmd)

-   [Reconciling PMT data](pmtbase/pmt_reconcile_data.qmd)

-   [Implications of reconciliation for revenue](pmtbase/pmt_forecast.qmd)

-   Deferred to a subsequent meeting:

    -   Constitutional ways to credit PMT against income tax. Also, MTA passes that employers can give out to employees?

    -   Getting a share of the pass-through entity tax - how does it work?

    -   State-imposed property tax surcharge in the region

    -   Options, options, options

-   Other near-term priorities?

-   Contract status

-   Reminder that I will be away:

    -   Sept 21-23

    -   Sept 28-Oct 14

### August 26, 2022

-   [Impact of 2011 payroll mobility tax changes](pmtbase/pmt_legislation.qmd)

-   Approaches to [making the payroll tax progressive](options/progressivity.qmd)

-   Review first-cut list of [revenue options](options/revenue_options.qmd)

-   Other discussion topics?

-   Schedule next week (I may not be able to do a Friday meeting)

-   Next steps

### August 19, 2022

-   Review revenue included in baseline analysis (see [this](https://docs.google.com/spreadsheets/d/1lzmDe7Zj1fQ4jDk9och5FPGFEMEYKkk2Og_UKkH0soY/edit#gid=888771929))

-   Analysis of [payroll mobility tax base](pmtbase/payroll_mobility_tax_base.qmd)

-   Review themes and templates for [revenue options](options/revenue_options.qmd)

-   FYI - I added a discussion on the [incidence of payroll taxes](taxes/payroll_mobility_tax.qmd#incidence)

-   Other discussion topics?

-   Next steps

-   Contract and billing

### August 12, 2022

-   Review goals

-   Review revenue included in analysis

### July 29, 2022 (phone call)

-   Review goals

-   Review timetable
