# Making the payroll mobility tax progresssive

Possible approaches:

-   Create a progressive rate structure

-   Flat rate but with an income tax credit

-   Other?

## Progressive rate structure

### Basic idea

Impose graduated rates where marginal or average tax rates rise as wages rise. For example, impose an income-tax-like schedule with rates applied to *each individual's* quarterly wages as follows:

+-------------------------+--------------------+---------------------------------------+--------------------------------------+----------------+----------------+
| Quarterly wage range    | Quarterly base tax | Plus rate on excess over lower amount | Example: quarterly / annualized wage | Example:\      | Effective rate |
|                         |                    |                                       |                                      | Annualized tax |                |
+=========================+===================:+======================================:+=====================================:+===============:+================+
| \$0 -\< \$10,000        | \$0                | 0%                                    | \$0 / \$0                            | \$0            | 0%             |
+-------------------------+--------------------+---------------------------------------+--------------------------------------+----------------+----------------+
| \$10,000 - \< \$20,000  | \$0                | 0.25%                                 | \$15k / \$60k                        | \$50           | 0.083%         |
+-------------------------+--------------------+---------------------------------------+--------------------------------------+----------------+----------------+
| \$20,000 - \< \$30,000  | \$25               | 0.35%                                 | \$25k / \$100k                       | \$170          | 0.17%          |
+-------------------------+--------------------+---------------------------------------+--------------------------------------+----------------+----------------+
| \$30,000 - \< \$100,000 | \$60               | 0.45%                                 | \$50k / \$200k                       | \$600          | 0.30%          |
+-------------------------+--------------------+---------------------------------------+--------------------------------------+----------------+----------------+
| \>= \$100,000           | \$375              | 1.00%                                 | \$250k / \$1m                        | \$7,500        | 0.75%          |
+-------------------------+--------------------+---------------------------------------+--------------------------------------+----------------+----------------+

### Considerations

What (if anything) to do about:

-   People who hold multiple jobs in the MTA region? E.g., someone who earns \$5k quarterly at 3 different jobs (\$15k in total) - pays no tax in example above but would pay \$50 annually if one job.

-   A person holds serial jobs in a quarter, each of which pays a high wage but none of which pushes the person into a high wage bracket for the quarter because of short duration.

-   A married couple living outside the MCTD, where a non-commuting spouse earns \$500k annually and the commuting-into-MCTD spouse earns \$75k. Taxed as if lower income, even though in practical terms they are an upper income couple.

-   A person who earns \$75k at a job in the MCTD, and \$425k through self employment outside of the MCTD. Taxed as lower income, even though in practical terms the person is an upper-income person.

If there is no annual reconciliation process to address these issues, these seeming inequities would exist; we'd want to figure out if they are just inequities, or unconstitutional inequities.

### Does any government have a graduated payroll tax?

I haven't found one yet.

### Next steps

More-thorough search for a progressive wage tax. Discussions with tax administrators and outside tax attorneys about how to implement such a tax.

## Flat rate with income tax credit

### Basic idea

Keep or increase the payroll mobility tax. Provide a (probably NYS rather than NYC) credit for lower-income taxpayers based on amount of credit. Can control the progressivity.

### Considerations

-   What to do about nonfilers of income tax?

-   Should the credit be refundable?

-   Should withholding be adjusted to take into account the eventual credit?

### Next steps

Discussions with tax administrators and outside tax attorneys about how to implement such a tax.
